### ISSUE TITLE
vim should open in terminal current dir

### ISSUE THREAD

**Issue by ushitora-anqou** [hiromi-mi/vim-TermSingleton#2]
vim-TermSingleton opens a file in the Vim current directory, not the terminal current directory.
In other words, the result of `pwd` in the terminal is different from the one of `:pwd` in the window of Vim.
It should be the same.

**Comment by hiromi-mi** [comment]
This behaviour was changed in commit [fc2473](https://github.com/hiromi-mi/vim-TermSingleton/commit/fc2473f47cb7a61ff848ab1bdc784683c65b9a8e)
